INSERT INTO products (product_name, product_url, product_price) VALUES
  ('Product 1', 'http://example.com/product1', 10.99),
  ('Product 2', 'http://example.com/product2', 19.99),
  ('Product 3', 'http://example.com/product3', 7.99),
  ('Product 4', 'http://example.com/product4', 14.99),
  ('Product 5', 'http://example.com/product5', 5.99),
  ('Product 6', 'http://example.com/product6', 12.99),
  ('Product 7', 'http://example.com/product7', 8.99),
  ('Product 8', 'http://example.com/product8', 17.99),
  ('Product 9', 'http://example.com/product9', 9.99),
  ('Product 10', 'http://example.com/product10', 11.99);

INSERT INTO products (product_name, product_url, product_price) VALUES
  ('Product 1', 'http://example.com/product1', 13.99),
  ('Product 2', 'http://example.com/product2', 21.99),
  ('Product 3', 'http://example.com/product3', 9.99),
  ('Product 4', 'http://example.com/product4', 16.99),
  ('Product 5', 'http://example.com/product5', 7.49),
  ('Product 6', 'http://example.com/product6', 14.49),
  ('Product 7', 'http://example.com/product7', 11.99),
  ('Product 8', 'http://example.com/product8', 19.99),
  ('Product 9', 'http://example.com/product9', 12.99),
  ('Product 10', 'http://example.com/product10', 15.99),
  ('Product 1', 'http://example.com/product1', 8.99),
  ('Product 2', 'http://example.com/product2', 23.99),
  ('Product 3', 'http://example.com/product3', 6.99),
  ('Product 4', 'http://example.com/product4', 18.99),
  ('Product 5', 'http://example.com/product5', 4.99),
  ('Product 6', 'http://example.com/product6', 10.99),
  ('Product 7', 'http://example.com/product7', 13.49),
  ('Product 8', 'http://example.com/product8', 20.99),
  ('Product 9', 'http://example.com/product9', 11.49),
  ('Product 10', 'http://example.com/product10', 14.49);

INSERT INTO products (product_name, product_url, product_price) VALUES
  ('Product 2', 'http://example.com/product2', 21.99),
  ('Product 4', 'http://example.com/product4', 16.99),
  ('Product 6', 'http://example.com/product6', 14.49),
  ('Product 8', 'http://example.com/product8', 19.99),
  ('Product 10', 'http://example.com/product10', 15.99),
  ('Product 2', 'http://example.com/product2', 23.99),
  ('Product 4', 'http://example.com/product4', 18.99),
  ('Product 6', 'http://example.com/product6', 10.99),
  ('Product 8', 'http://example.com/product8', 20.99),
  ('Product 10', 'http://example.com/product10', 14.49);
